runtime: nodejs20
env: standard

service: backend

instance_class: F4_1G

handlers:
- url: /build/static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

runtime_config:
  document_root: .
  skip_lockdown_document_root: true